import RenderResult from 'next/dist/server/render-result';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


type SearchResult = {
  proNumber: string;
  weight: number;
  pallets: number;
  pieces: number;
  pickupDate: string;
  serviceDate: string;
  shipmentTags: Array<string>;
  status: string;
};


const searchResults : SearchResult[] = [
  {
  proNumber : "1234567890",
  weight: 100,
  pallets:5,
  pieces : 20,
  pickupDate : "2023-03-18",
  serviceDate : "2023-03-20",
  shipmentTags : ["CC", "UC"],
  status : "Disabled"
  },
  
]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
 
}) {
  
    function renderResults(result: SearchResult) {
      return <div key={result.proNumber}>{result.proNumber}</div>;
    }
  
  return (
    <html lang="en">
      <body>
        <div>
          <input type="search" />
          <div>
      {
        searchResults.map(renderResults)
      }
     </div>
        </div>
        
        {children}</body>
    </html>
  )
}
